import type { Metadata } from "next";
import { Arimo } from "next/font/google";
import "./globals.css";

const arimoSans = Arimo({
  variable: "--font-Arimo-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
        <html lang="pt-br">
            <body
                className={`${arimoSans.variable} antialiased`}
            >
                <div className="min-h-screen w-full flex flex-col justify-center items-center py-20">
                    {children}
                </div>
            </body>
        </html>
    );
}
